### ISSUE TITLE
[Backend] Wrong information while retrieving Pending Follower Request List

### ISSUE THREAD

**Issue by bwqr** [bounswe/bounswe2019group6#213] opened 2019-11-24 14:11 UTC
**Describe the bug**
The incoming data contains the authorized user's name, not the user who sent a follow request.
**To Reproduce**
1. Send a follow request to a private user.
2. Check the pending follower request of private user.

**Expected behavior**
The username should contain sender's name.

**Current behavior**
The username belongs to requested user.

**Possible Solution**
Interchange them.

**Additional context**

**Comment by burakikanyildiz** [comment] 2019-11-24 14:15
The problem is solved and merged to backend-dev branch. Also new functionalities added to backend-dev. You can check it out!. Thanks for the feedback.

**Closed by burakikanyildiz** 2019-11-24 14:15 UTC
Labels: related:backend, type:bug
